
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx2pk5lIbPGer6eU-EVamKhPBbCYi1jTY',
    appId: '1:717875328757:android:3e8697dcbddd80ff0af7bc',
    messagingSenderId: '717875328757',
    projectId: 'student-instructor-app',
    storageBucket: 'student-instructor-app.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4G--SoRAtZ5FQEpmxF1ERz2UWmn-65o',
    authDomain: 'student-instructor-app.firebaseapp.com',
    projectId: 'student-instructor-app',
    storageBucket: 'student-instructor-app.appspot.com',
    messagingSenderId: '717875328757',
    appId: '1:717875328757:web:609c0d8b6466848a0af7bc',
    measurementId: 'G-G36L2L5ZX3'
  );
}
